version: "3.9"
services:
  redis:
    image: redis
    ports:
    - "6379:6379"
        
  percona:
    image: "percona:8.0"
    volumes:
      - db-data:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

        
  phpmyadmin:
    image: "phpmyadmin"
    ports:
    - "8080:80"
    depends_on:
      - percona
    environment:
      - PMA_HOST=percona
        
volumes: 
  db-data:
      